install_atom: true
install_keepassx: true
install_chrome: true
install_slack: true
install_dropbox: true
install_spotify: true
install_node: true
install_ruby: true

# PHP configuration.
php_packages:
  - php5-common
  - php5-cli
  - php5-dev
  - libpcre3-dev
  - php5-gd
  - php5-curl
  - php5-imap
  - php5-json
  - php5-opcache
  - php5-xml
  - php5-mbstring
  - php-sqlite3
  - php-apcu
