install_atom: true
install_keepassx: true
install_chrome: true
install_slack: true
install_dropbox: true
install_spotify: true
install_node: true
install_ruby: true
install_virtualbox: true
manativm: false

# PHP configuration.
php_packages:
  - php7.1-common
  - php7.1-cli
  - php7.1-dev
  - libpcre3-dev
  - php7.1-gd
  - php7.1-curl
  - php7.1-imap
  - php7.1-json
  - php7.1-opcache
  - php7.1-xml
  - php7.1-mbstring
  - php-sqlite3
  - php-apcu
