---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - ../config.yml

  gather_facts: False
  pre_tasks:
    - include: tasks/init.yml
    - include: tasks/init-debian.yml

  roles:
    # Essential roles.
    - geerlingguy.git
    - dwcramer.ansible
    - andrewrothstein.vagrant
    - { role: wtanaka.virtualbox, when: install_virtualbox }
    - { role: gvillalta99.nvm, when: install_node }
    - { role: altermn.rvm, when: install_ruby }
    - geerlingguy.drush
    - { role: kporras07.terminus, become: no }
    - { role: Trozz.atom, when: install_atom }
    - { role: wtanaka.keepassx, when: install_keepassx }
    - { role: wtanaka.chrome, when: install_chrome }
    - { role: wtanaka.slack, when: install_slack }
    - { role: wtanaka.dropbox, when: install_dropbox }
    - { role: iknite.spotify, when: install_spotify }
