---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - ../config.yml

  gather_facts: False
  pre_tasks:
    - include: tasks/init.yml
    - include: tasks/init-debian.yml

  roles:
    # Essential roles.
    - dwcramer.ansible
    - andrewrothstein.vagrant
    - geerlingguy.drush
