---
- src: geerlingguy.git
- src: dwcramer.ansible
- src: andrewrothstein.vagrant
- src: wtanaka.virtualbox
- src: gvillalta99.nvm
- src: altermn.rvm
- src: geerlingguy.drush
- src: kporras07.terminus
- src: Trozz.atom
- src: wtanaka.keepassx
- src: wtanaka.chrome
- src: wtanaka.slack
- src: wtanaka.dropbox
- src: iknite.spotify
