---
- src: geerlingguy.git
- src: dwcramer.ansible
- src: andrewrothstein.vagrant
- src: wtanaka.virtualbox
- src: gvillalta99.nvm
- src: altermn.rvm
- src: geerlingguy.drush
- src: trozz.atom
- src: wtanaka.keepassx
- src: wtanaka.chrome
